spring:
 #Configuración MySQL
  datasource:
    #url: jdbc:mysql://localhost:3306/bobinado?allowPublicKeyRetrieval=true&useSSL=false&useTimezone=true&serverTimezone=GMT&characterEncoding=UTF-8
    #username: root
    #password: root
    #Configuracion heroku
    url: jdbc:mysql://bwryhx9wv9wftgfi5drh-mysql.services.clever-cloud.com:3306/bwryhx9wv9wftgfi5drh?allowPublicKeyRetrieval=true&useSSL=false&useTimezone=true&serverTimezone=GMT&characterEncoding=UTF-8
    username: ut02fuhqwrusflzl
    password: wwX1qaftSb8aacf3R0Ri
    driver-class-name: com.mysql.cj.jdbc.Driver
#Configuración Creación de tablas (Hibernate)
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #dialect: org.hibernate.dialect.MySQL8InnoDBDialect
        ##configugracion heroku
        dialect: org.hibernate.dialect.MySQL8Dialect
    #database-platform: 
#Que thymeleaf no guarde datos en cache
  thymeleaf:
    cache: false